import { Injectable } from '@angular/core';
import { Markings } from '../Models/Beast';

@Injectable({
  providedIn: 'root',
})
export class BreedingService {
  constructor() {}
  private _markingsDB: Markings[] = [
    { name: 'badger', rarity: 'common' },
    { name: 'bald', rarity: 'common' },
    { name: 'banded', rarity: 'common' },
    { name: 'bullseye', rarity: 'common' },
    { name: 'dipped', rarity: 'common' },
    { name: 'dust', rarity: 'common' },
    { name: 'highway', rarity: 'common' },
    { name: 'nimbus', rarity: 'common' },
    { name: 'pangare', rarity: 'common' },
    { name: 'patch', rarity: 'common' },
    { name: 'scruff', rarity: 'common' },
    { name: 'siamese', rarity: 'common' },
    { name: 'sika', rarity: 'common' },
    { name: 'tar', rarity: 'common' },
    { name: 'unders', rarity: 'common' },
    { name: 'appaloosa', rarity: 'uncommon' },
    { name: 'dapple', rarity: 'uncommon' },
    { name: 'fox', rarity: 'uncommon' },
    { name: 'garter', rarity: 'uncommon' },
    { name: 'glossy', rarity: 'uncommon' },
    { name: 'sable', rarity: 'uncommon' },
    { name: 'spotting', rarity: 'uncommon' },
    { name: 'streak', rarity: 'uncommon' },
    { name: 'stripes', rarity: 'uncommon' },
    { name: 'dun', rarity: 'uncommon' },
    { name: 'avian', rarity: 'uncommon' },
    { name: 'points', rarity: 'uncommon' },
    { name: 'frosted', rarity: 'uncommon' },
    { name: 'rabicano', rarity: 'uncommon' },
    { name: 'sooty', rarity: 'uncommon' },
    { name: 'ink', rarity: 'uncommon' },
    { name: 'mask', rarity: 'uncommon' },
    { name: 'gazelle', rarity: 'uncommon' },
    { name: 'cheekdot', rarity: 'uncommon' },
    { name: 'hooded', rarity: 'uncommon' },
    { name: 'blotched', rarity: 'uncommon' },
    { name: 'molted', rarity: 'uncommon' },
    { name: 'misty', rarity: 'rare' },
    { name: 'pied', rarity: 'rare' },
    { name: 'raindrop', rarity: 'rare' },
    { name: 'roan', rarity: 'rare' },
    { name: 'speckles', rarity: 'rare' },
    { name: 'tapir', rarity: 'rare' },
    { name: 'clouded leopard', rarity: 'rare' },
    { name: 'ocelot', rarity: 'rare' },
    { name: 'rosette', rarity: 'rare' },
    { name: 'tabby', rarity: 'rare' },
    { name: 'jackal', rarity: 'rare' },
    { name: 'merle', rarity: 'rare' },
    { name: 'bloodmark', rarity: 'rare' },
    { name: 'camo', rarity: 'rare' },
    { name: 'lacing', rarity: 'rare' },
    { name: 'honeymark', rarity: 'rare' },
    { name: 'saimaa', rarity: 'rare' },
    { name: 'shield', rarity: 'rare' },
    { name: 'artic', rarity: 'rare' },
  ];
}
