import { Injectable } from '@angular/core';
import { gameitems, redeemItem } from '../Models/Game-item';

@Injectable({
  providedIn: 'root',
})
export class ItemsService {
  constructor() {}

  //#region FakeDB
  private _database: gameitems[] = [
    {
      name: 'broken bow string',
      category: 'hunting',
      price: 20,
      redeemType: 'activities',
    },
    {
      name: 'mauled pelt',
      category: 'hunting',
      price: 40,
      redeemType: 'activities',
    },
    {
      name: 'dewclaw',
      category: 'hunting',
      price: 60,
      redeemType: 'activities',
    },
    {
      name: 'cloven hooves',
      category: 'hunting',
      price: 80,
      redeemType: 'activities',
    },
    {
      name: 'cave bear claws',
      category: 'hunting',
      price: 100,
      redeemType: 'activities',
    },
    {
      name: 'warm wolf fur',
      category: 'hunting',
      price: 200,
      redeemType: 'activities',
    },
    {
      name: 'handful of predator teeth',
      category: 'hunting',
      price: 230,
      redeemType: 'activities',
    },
    {
      name: 'pristine lion fangs',
      category: 'hunting',
      price: 260,
      redeemType: 'activities',
    },
    {
      name: 'elk pelt',
      category: 'hunting',
      price: 300,
      redeemType: 'activities',
    },
    {
      name: 'striped pelt',
      category: 'hunting',
      price: 400,
      redeemType: 'activities',
    },
    {
      name: 'silky albino fur',
      category: 'hunting',
      price: 450,
      redeemType: 'activities',
    },
    {
      name: 'wooly rhino horn',
      category: 'hunting',
      price: 500,
      redeemType: 'activities',
    },
    {
      name: 'cursed mammoth tusk',
      category: 'hunting',
      price: 700,
      redeemType: 'activities',
    },
    {
      name: 'chimeric pelt',
      category: 'hunting',
      price: 800,
      redeemType: 'activities',
    },
    { name: 'coral', category: 'fishing', price: 20, redeemType: 'activities' },
    {
      name: 'Eurypterid',
      category: 'fishing',
      price: 40,
      redeemType: 'activities',
    },
    {
      name: 'succulent fish meat',
      category: 'fishing',
      price: 60,
      redeemType: 'activities',
    },
    {
      name: 'black coelacanth',
      category: 'fishing',
      price: 80,
      redeemType: 'activities',
    },
    {
      name: 'sabertooth salmon',
      category: 'fishing',
      price: 100,
      redeemType: 'activities',
    },
    {
      name: 'Ammonite Shell',
      category: 'fishing',
      price: 200,
      redeemType: 'activities',
    },
    {
      name: 'Golden Coelacanth Scale',
      category: 'fishing',
      price: 200,
      redeemType: 'activities',
    },
    {
      name: 'Large Shining Scale',
      category: 'fishing',
      price: 200,
      redeemType: 'activities',
    },
    {
      name: 'Nothosaurus claw',
      category: 'fishing',
      price: 230,
      redeemType: 'activities',
    },
    {
      name: 'Henodus shell',
      category: 'fishing',
      price: 260,
      redeemType: 'activities',
    },
    {
      name: 'thalassomedon skull',
      category: 'fishing',
      price: 300,
      redeemType: 'activities',
    },
    {
      name: 'opabinia',
      category: 'fishing',
      price: 400,
      redeemType: 'activities',
    },
    {
      name: 'horseshoe crab shell',
      category: 'fishing',
      price: 450,
      redeemType: 'activities',
    },
    {
      name: 'megalodon tooth',
      category: 'fishing',
      price: 500,
      redeemType: 'activities',
    },
    {
      name: 'dunkleosteus',
      category: 'fishing',
      price: 700,
      redeemType: 'activities',
    },
    {
      name: 'megalodon carcass',
      category: 'fishing',
      price: 800,
      redeemType: 'activities',
    },
    {
      name: 'ochre',
      category: 'discovery',
      price: 20,
      redeemType: 'activities',
    },
    {
      name: 'leather strips',
      category: 'discovery',
      price: 40,
      redeemType: 'activities',
    },
    {
      name: 'sharpened flint',
      category: 'discovery',
      price: 60,
      redeemType: 'activities',
    },
    {
      name: 'sinew rope',
      category: 'discovery',
      price: 80,
      redeemType: 'activities',
    },
    {
      name: 'woven basket',
      category: 'discovery',
      price: 100,
      redeemType: 'activities',
    },
    {
      name: 'assorted feathers',
      category: 'discovery',
      price: 200,
      redeemType: 'activities',
    },
    {
      name: 'ancient jewelry',
      category: 'discovery',
      price: 230,
      redeemType: 'activities',
    },
    {
      name: 'antler spear head',
      category: 'discovery',
      price: 260,
      redeemType: 'activities',
    },
    {
      name: 'sturdy lumber',
      category: 'discovery',
      price: 300,
      redeemType: 'activities',
    },
    {
      name: 'ancient metal ring',
      category: 'discovery',
      price: 400,
      redeemType: 'activities',
    },
    {
      name: 'jagged tooth knife',
      category: 'discovery',
      price: 450,
      redeemType: 'activities',
    },
    {
      name: 'obsidian blade',
      category: 'discovery',
      price: 500,
      redeemType: 'activities',
    },
    {
      name: 'Moonsteel bar',
      category: 'discovery',
      price: 700,
      redeemType: 'activities',
    },
    {
      name: 'skyfire diamond',
      category: 'discovery',
      price: 800,
      redeemType: 'activities',
    },
    {
      name: 'golden sabertooth idol',
      category: 'discovery',
      price: 3000,
      redeemType: 'equip',
    },
    {
      name: 'seeds',
      category: 'foraging',
      price: 20,
      redeemType: 'activities',
    },
    {
      name: 'tomato',
      category: 'foraging',
      price: 40,
      redeemType: 'activities',
    },
    {
      name: 'potato',
      category: 'foraging',
      price: 60,
      redeemType: 'activities',
    },
    {
      name: 'chamomile',
      category: 'foraging',
      price: 80,
      redeemType: 'activities',
    },
    {
      name: 'marigold',
      category: 'foraging',
      price: 100,
      redeemType: 'activities',
    },
    {
      name: 'berries',
      category: 'foraging',
      price: 200,
      redeemType: 'activities',
    },
    {
      name: 'apple',
      category: 'foraging',
      price: 230,
      redeemType: 'activities',
    },
    {
      name: 'mint',
      category: 'foraging',
      price: 260,
      redeemType: 'activities',
    },
    {
      name: 'aloe vera',
      category: 'foraging',
      price: 300,
      redeemType: 'activities',
    },
    {
      name: 'catnip',
      category: 'foraging',
      price: 400,
      redeemType: 'activities',
    },
    {
      name: 'parsnip',
      category: 'foraging',
      price: 450,
      redeemType: 'activities',
    },
    {
      name: 'hawthorn',
      category: 'foraging',
      price: 500,
      redeemType: 'activities',
    },
    {
      name: 'strawberries',
      category: 'foraging',
      price: 700,
      redeemType: 'activities',
    },
    {
      name: 'cherries',
      category: 'foraging',
      price: 800,
      redeemType: 'activities',
    },
    {
      name: 'titanoboa scales',
      category: 'telt',
      price: 220,
      redeemType: 'activities',
    },
    {
      name: 'passion fruit',
      category: 'telt',
      price: 240,
      redeemType: 'activities',
    },
    { name: 'vanilla', category: 'telt', price: 260, redeemType: 'activities' },
    {
      name: 'red clay brick',
      category: 'telt',
      price: 280,
      redeemType: 'activities',
    },
    {
      name: 'turquoise',
      category: 'telt',
      price: 300,
      redeemType: 'activities',
    },
    {
      name: 'snake figuring',
      category: 'telt',
      price: 400,
      redeemType: 'activities',
    },
    {
      name: 'chunk of obsidian',
      category: 'telt',
      price: 430,
      redeemType: 'activities',
    },
    {
      name: 'jade bracelet',
      category: 'telt',
      price: 460,
      redeemType: 'activities',
    },
    {
      name: 'jaguar statuette',
      category: 'telt',
      price: 500,
      redeemType: 'activities',
    },
    {
      name: 'sarcosuchus tooth',
      category: 'telt',
      price: 600,
      redeemType: 'activities',
    },
    {
      name: 'quetzal feathers',
      category: 'telt',
      price: 650,
      redeemType: 'activities',
    },
    {
      name: 'golden coin',
      category: 'telt',
      price: 700,
      redeemType: 'activities',
    },
    {
      name: 'sarchosuchus',
      category: 'telt',
      price: 900,
      redeemType: 'activities',
    },
    {
      name: 'headdress amulet',
      category: 'telt',
      price: 1000,
      redeemType: 'activities',
    },
    {
      name: 'Obsidian Saber',
      category: 'telt',
      price: 3000,
      redeemType: 'equip',
    },
    {
      name: 'wandering ancient',
      category: 'telt',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'Calendar Piece: death',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: deer',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: dog',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: eagle',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: fire',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: flint',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: grass',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: jaguar',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: lizard',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: monkey',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: moon',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: motion',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: rabbit',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: rain',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: reed',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: sarco',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: snake',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: temple',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: vulture',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Calendar Piece: water',
      category: 'calendar',
      price: 350,
      redeemType: 'calendar',
    },
    {
      name: 'Tawny Hyaenodon',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'spotted Hyaenodon',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'striped Hyaenodon',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'bicolor Hyaenodon',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'tawny Thylacine',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'golden Thylacine',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'pied Thylacine',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'brown Jerboa',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'black Jerboa',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'pied Jerboa',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'tawny Eucladoceros',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'spotted Eucladoceros',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'cream Eucladoceros',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'Red Warrah',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'Black Warrah',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'Striped Warrah',
      category: 'companions',
      price: 200,
      redeemType: 'equip',
    },
    {
      name: 'tawny Cave Lion Cub',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'spotted Cave Lion Cub',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Melanistic Cave Lion Cub',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'ivory Megalania',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'nightstalker Megalania',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'snowblind Daeodon',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'silvermane Daeodon',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'stripehide Daeodon',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'spotted Gorgonops',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'red sable Gorgonops',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'melanistic Gorgonops',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'brown Trilobite',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'blue grey Trilobite',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'great white Baby Thalattoarchon',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'coral reef Baby Thalattoarchon',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'erythristic Baby Thalattoarchon',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'liver Gomphotaria',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'raindrop glacier Gomphotaria',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'shadow vitiligo Gomphotaria',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'blue Coelacanth',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'earth Coelacanth',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'white Coelacanth',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'stonejaw Titanoboa',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'dunestrike Titanoboa',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'albino diamond Titanoboa',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'warm clay Cistecephalus',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'sunrise Cistecephalus',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'bicolor Cistecephalus',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'tundra Muskox Calf',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'snowstorm Muskox Calf',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'cloudhorn Muskox Calf',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'common grey Pigeon',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'pied Pigeon',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'barred oriental Pigeon',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'sunrunner Hyracotherium',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'twilight Hyracotherium',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Koi Hyracotherium',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'gray Saber Squirrel',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'darkwood Saber Squirrel',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'fire melanistic Saber Squirrel',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'muddy Baby Metridiochoerus',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'pied Baby Metridiochoerus',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'darkwood Baby Metridiochoerus',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'oakfist Chalicotherium',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'dustback Chalicotherium',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'marbleside Chalicotherium',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Pink Dodo',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Blue Dodo',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Albino Dodo',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Brown Wooly Rhino Calf',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'White Wooly Rhino Calf',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Bicolor Wooly Rhino Calf',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Dun Equus Foal',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Cream Dun Equus Foal',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Pied Palomino Equus Foal',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Moonblessed Equus Foal',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Black Terror Bird Chick',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Spotted Terror Bird Chick',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Pink Terror Bird Chick',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Brown Moose',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Albino Moose',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Pied Moose',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Spotted Megaloceros',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Earthen Megaloceros',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Cream Megaloceros',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Brown Wolverine',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Blone Striped Wolverine',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Snowstalker Wolverine',
      category: 'companions',
      price: 400,
      redeemType: 'equip',
    },
    {
      name: 'Pygmy Onyc',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'Albino Pygmy Onyc',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'Badger Pygmy Onyc',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'Polar Cave Bear Cub',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'Brown Cave Bear Cub',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'Glacier Cave Bear Cub',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'spotted spring bunny',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'brown spring bunny',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'Earthen Striped Chriacus',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'Golden Chriacus',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'Moonblessed Chriacus',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'royal gala worg puppy',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'panda worg puppy',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'ruby worg puppy',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    { name: 'Huxli', category: 'companions', price: 1000, redeemType: 'equip' },
    {
      name: 'Luxili',
      category: 'companions',
      price: 1000,
      redeemType: 'equip',
    },
    {
      name: 'Jungle Jaguar Cub',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'Golden Jaguar Cub',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'Black Jaguar Cub',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'Ginger Jaguar Cub',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'Calico Jaguar Cub',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'Pied Jaguar Cub',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'fawn Tapir',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'banded Tapir',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'striped Tapir',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'brown Josephoartigasia',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'cream Josephoartigasia',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'bicolor Josephoartigasia',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'swamp Glyptodon',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'mud Glyptodon',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'golden Glyptodon',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'sand Macrauchenia',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'savannah Macrauchenia',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'moonblessed Macrauchenia',
      category: 'companions',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'Spectral Trilobite',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Golden Coelacanth',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Winter Festival Reindeer',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Blue Moon Jellyfish',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Violet Moon Jellyfish',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Jynx, the sweet pea',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    { name: 'Impy', category: 'companions', price: 0, redeemType: 'equip' },
    {
      name: 'dima, the baby mammoth',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'red lore keeper familiar',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'blue lore keeper familiar',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: "hasswei''s familiar",
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: "larkka''s familiar",
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: "Umbru''s Familiar",
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: "Purrtato''s minion",
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Cloverbite',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'mr. bunbun',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: "Mamota''s Messenger",
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'striped otter',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'toasty marshmallow',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Earthen Mesonyx',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Pied Mesonyx',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Sunray Mesonyx',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Mr. Crayfish',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Arco, the Archelon Hoarder',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'will o wisp',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'Crismun Fex, the Ice Dancer',
      category: 'companions',
      price: 0,
      redeemType: 'equip',
    },
    { name: 'stardust', category: 'event', price: 100, redeemType: 'currency' },
    {
      name: 'moonstone',
      category: 'event',
      price: 500,
      redeemType: 'activities',
    },
    {
      name: 'celestial bead',
      category: 'event',
      price: 700,
      redeemType: 'activities',
    },
    {
      name: 'crescent moon bead',
      category: 'event',
      price: 900,
      redeemType: 'activities',
    },
    {
      name: 'ghost cookie',
      category: 'event',
      price: 100,
      redeemType: 'currency',
    },
    {
      name: 'bloody mask',
      category: 'event',
      price: 400,
      redeemType: 'activities',
    },
    {
      name: 'gnarled branch',
      category: 'event',
      price: 500,
      redeemType: 'activities',
    },
    {
      name: 'spiderweb',
      category: 'event',
      price: 600,
      redeemType: 'activities',
    },
    {
      name: 'unidentified fang',
      category: 'event',
      price: 600,
      redeemType: 'activities',
    },
    {
      name: 'jack-o-lantern',
      category: 'event',
      price: 700,
      redeemType: 'activities',
    },
    {
      name: 'ghastly lantern',
      category: 'event',
      price: 800,
      redeemType: 'activities',
    },
    {
      name: "sorcerers'' notes",
      category: 'event',
      price: 900,
      redeemType: 'activities',
    },
    {
      name: 'festive tree cookie',
      category: 'event',
      price: 100,
      redeemType: 'currency',
    },
    {
      name: 'poinsettia',
      category: 'event',
      price: 400,
      redeemType: 'activities',
    },
    {
      name: 'pine branch',
      category: 'event',
      price: 500,
      redeemType: 'activities',
    },
    {
      name: 'hefty elk haunch',
      category: 'event',
      price: 600,
      redeemType: 'activities',
    },
    {
      name: 'chocolate wreath cookie',
      category: 'event',
      price: 700,
      redeemType: 'activities',
    },
    {
      name: 'mistletoe',
      category: 'event',
      price: 800,
      redeemType: 'activities',
    },
    { name: 'sunstone', category: 'event', price: 100, redeemType: 'currency' },
    {
      name: 'red rose',
      category: 'event',
      price: 400,
      redeemType: 'activities',
    },
    {
      name: 'sweet hearts',
      category: 'event',
      price: 500,
      redeemType: 'activities',
    },
    {
      name: 'chocolates',
      category: 'event',
      price: 600,
      redeemType: 'activities',
    },
    {
      name: 'pink rose',
      category: 'event',
      price: 600,
      redeemType: 'activities',
    },
    {
      name: 'caramel hearts',
      category: 'event',
      price: 800,
      redeemType: 'activities',
    },
    {
      name: 'sacred water',
      category: 'event',
      price: 100,
      redeemType: 'currency',
    },
    {
      name: 'green egg',
      category: 'event',
      price: 400,
      redeemType: 'activities',
    },
    {
      name: 'colorful egg',
      category: 'event',
      price: 500,
      redeemType: 'activities',
    },
    {
      name: 'sunset egg',
      category: 'event',
      price: 600,
      redeemType: 'activities',
    },
    {
      name: 'rainy egg',
      category: 'event',
      price: 600,
      redeemType: 'activities',
    },
    {
      name: 'pink tulip',
      category: 'event',
      price: 700,
      redeemType: 'activities',
    },
    {
      name: 'carrots',
      category: 'event',
      price: 800,
      redeemType: 'activities',
    },
    {
      name: 'golden egg',
      category: 'event',
      price: 1500,
      redeemType: 'activities',
    },
    {
      name: 'birthday cake',
      category: 'event',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'handful of relic fragments',
      category: 'event',
      price: 100,
      redeemType: 'currency',
    },
    {
      name: 'pouch of relic fragments',
      category: 'event',
      price: 250,
      redeemType: 'currency',
    },
    {
      name: 'bag of relic fragments',
      category: 'event',
      price: 500,
      redeemType: 'currency',
    },
    {
      name: 'golden apple',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'celestial satchel',
      category: 'event',
      price: 1500,
      redeemType: 'reveal',
    },
    {
      name: 'clump of moss',
      category: 'event',
      price: 1000,
      redeemType: 'reveal',
    },
    { name: 'grimoire', category: 'event', price: 0, redeemType: 'reveal' },
    {
      name: 'hot chocolate',
      category: 'event',
      price: 900,
      redeemType: 'reveal',
    },
    { name: 'log cake', category: 'event', price: 200, redeemType: 'reveal' },
    {
      name: 'lovely note',
      category: 'event',
      price: 700,
      redeemType: 'reveal',
    },
    {
      name: 'valentines candle',
      category: 'event',
      price: 900,
      redeemType: 'reveal',
    },
    { name: 'bouquet', category: 'event', price: 900, redeemType: 'reveal' },
    {
      name: 'chocolate eggs',
      category: 'event',
      price: 900,
      redeemType: 'reveal',
    },
    {
      name: 'golden fox bell',
      category: 'event',
      price: 1500,
      redeemType: 'oneTimeUse',
    },
    {
      name: 'carrot cake',
      category: 'event',
      price: 1500,
      redeemType: 'oneTimeUse',
    },
    {
      name: 'wiggling burlap sack',
      category: 'Reveal',
      price: 10,
      redeemType: 'reveal',
    },
    {
      name: 'chewed up hunters pack',
      category: 'reveal',
      price: 10,
      redeemType: 'reveal',
    },
    {
      name: 'clawed medicinal bag',
      category: 'reveal',
      price: 10,
      redeemType: 'reveal',
    },
    {
      name: 'carefully wrapped hide package',
      category: 'reveal',
      price: 10,
      redeemType: 'reveal',
    },
    {
      name: 'fertility pouch',
      category: 'reveal',
      price: 10,
      redeemType: 'reveal',
    },
    {
      name: 'bloodied string of beads',
      category: 'reveal',
      price: 10,
      redeemType: 'reveal',
    },
    {
      name: 'polished wooden beads',
      category: 'reveal',
      price: 10,
      redeemType: 'reveal',
    },
    {
      name: 'abandoned saber kitten',
      category: 'reveal',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'abandoned dire worg pup',
      category: 'reveal',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'abandoned equus foal',
      category: 'reveal',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'abandoned ursus cub',
      category: 'reveal',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'abandoned megaloceros calf',
      category: 'reveal',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'abandoned terror bird chick',
      category: 'reveal',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'abandoned woolly mammoth calf',
      category: 'reveal',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'sinew bound chest',
      category: 'reveal',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'overflowing treasure chest',
      category: 'reveal',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'rusty lockbox',
      category: 'reveal',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'loot-filled pumpkin',
      category: 'reveal',
      price: 0,
      redeemType: 'reveal',
    },
    {
      name: 'giant oyster',
      category: 'reveal',
      price: 200,
      redeemType: 'reveal',
    },
    { name: 'lucky totem', category: 'tack', price: 750, redeemType: 'equip' },
    {
      name: 'sharpened spear',
      category: 'tack',
      price: 800,
      redeemType: 'equip',
    },
    {
      name: 'hide wrapped quiver',
      category: 'tack',
      price: 500,
      redeemType: 'equip',
    },
    {
      name: 'claw of the great hunt',
      category: 'tack',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'hand woven net',
      category: 'tack',
      price: 800,
      redeemType: 'equip',
    },
    { name: 'simple bait', category: 'tack', price: 500, redeemType: 'equip' },
    {
      name: 'glittering talisman',
      category: 'tack',
      price: 1500,
      redeemType: 'equip',
    },
    {
      name: 'warm bindings',
      category: 'tack',
      price: 800,
      redeemType: 'equip',
    },
    { name: 'map', category: 'tack', price: 500, redeemType: 'equip' },
    { name: 'muddy notes', category: 'tack', price: 1500, redeemType: 'equip' },
    {
      name: 'small plant bag',
      category: 'tack',
      price: 800,
      redeemType: 'equip',
    },
    { name: 'bone sickle', category: 'tack', price: 500, redeemType: 'equip' },
    {
      name: 'abandonned foraging basket',
      category: 'tack',
      price: 1500,
      redeemType: 'equip',
    },
    { name: 'machuahuilt', category: 'tack', price: 1500, redeemType: 'equip' },
    {
      name: 'headdress of the stars',
      category: 'tack',
      price: 2000,
      redeemType: 'equip',
    },
    {
      name: 'horn of beasts',
      category: 'tack',
      price: 1500,
      redeemType: 'equip',
    },
    { name: 'burning statue', category: 'tack', price: 0, redeemType: 'equip' },
    { name: 'runed talisman', category: 'tack', price: 0, redeemType: 'equip' },
    {
      name: 'adornments',
      category: 'cosmetic',
      price: 500,
      redeemType: 'cosmetic',
    },
    {
      name: 'magical adornments',
      category: 'cosmetic',
      price: 2000,
      redeemType: 'cosmetic',
    },
    {
      name: 'bowl of paints',
      category: 'cosmetic',
      price: 500,
      redeemType: 'cosmetic',
    },
    {
      name: 'battle wounds',
      category: 'cosmetic',
      price: 500,
      redeemType: 'cosmetic',
    },
    {
      name: 'eye changer',
      category: 'cosmetic',
      price: 2000,
      redeemType: 'cosmetic',
    },
    {
      name: 'expression changer',
      category: 'cosmetic',
      price: 2000,
      redeemType: 'cosmetic',
    },
    {
      name: 'ear changer',
      category: 'cosmetic',
      price: 2000,
      redeemType: 'cosmetic',
    },
    {
      name: 'witches wand',
      category: 'cosmetic',
      price: 500,
      redeemType: 'cosmetic',
    },
    {
      name: 'witches brew',
      category: 'cosmetic',
      price: 300,
      redeemType: 'cosmetic',
    },
    {
      name: 'custom title',
      category: 'cosmetic',
      price: 0,
      redeemType: 'cosmetic',
    },
    {
      name: 'blessing of umbru',
      category: 'cosmetic',
      price: 900,
      redeemType: 'cosmetic',
    },
    {
      name: 'moonflower',
      category: 'cosmetic',
      price: 900,
      redeemType: 'cosmetic',
    },
    {
      name: 'black rose',
      category: 'cosmetic',
      price: 900,
      redeemType: 'cosmetic',
    },
    {
      name: 'bone ornament',
      category: 'cosmetic',
      price: 900,
      redeemType: 'cosmetic',
    },
    {
      name: 'bone bracelet',
      category: 'cosmetic',
      price: 900,
      redeemType: 'cosmetic',
    },
    {
      name: 'stone of arwii',
      category: 'breeding',
      price: 300,
      redeemType: 'breedingGeno',
    },
    {
      name: 'ancient life rune',
      category: 'breeding',
      price: 600,
      redeemType: 'breedingGeno',
    },
    {
      name: 'false statue',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'crude steel statue',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'False donii',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'lovingly carved donii',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'roast',
      category: 'breeding',
      price: 1000,
      redeemType: 'breedingGeno',
    },
    {
      name: 'potion of wisdom',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'golden charm of bending',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'rainbow rose',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: "chris''s entourage",
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'silver apple',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'golden blood of arwii',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: "imdir''s horn",
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'umbru token',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'purified water of hathar',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'runic blessing of hasswei',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: "donii''s flower",
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'antlered skull',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'totem of ruda',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'feather of fury',
      category: 'breeding',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'fruit of arwii',
      category: 'geno',
      price: 1000,
      redeemType: 'breedingGeno',
    },
    {
      name: 'four leaf clover',
      category: 'geno',
      price: 1500,
      redeemType: 'breedingGeno',
    },
    {
      name: 'stitched bear',
      category: 'geno',
      price: 1500,
      redeemType: 'breedingGeno',
    },
    {
      name: 'potion of the night',
      category: 'geno',
      price: 2000,
      redeemType: 'breedingGeno',
    },
    {
      name: 'golden charm of shapeshifting',
      category: 'geno',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'golden charm of altering',
      category: 'geno',
      price: 0,
      redeemType: 'breedingGeno',
    },
    {
      name: 'Accident prone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 8,
    },
    {
      name: 'Befriender',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 8,
    },
    {
      name: 'Fortunes Favor',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 8,
    },
    {
      name: 'Opportunist',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 8,
    },
    {
      name: 'Survivor',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 8,
    },

    {
      name: 'call of the wild trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 18,
    },
    {
      name: 'evasive trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 18,
    },
    {
      name: 'loner trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 18,
    },
    {
      name: 'piercing blows trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 18,
    },
    {
      name: 'quick learner trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 18,
    },
    {
      name: 'fatal strikes trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 30,
    },
    {
      name: 'impressive stamina trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 30,
    },
    {
      name: 'treasure hunter trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 30,
    },
    {
      name: "larkka''s luck trait stone",
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 43,
    },
    {
      name: 'proud parent trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 43,
    },
    {
      name: 'silver tongue trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
      shards: 43,
    },
    {
      name: 'holiday cheer trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'pumkin-o-plenty trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'treasure seeker trait stone',
      category: 'trait',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: "ra''d''s frenzy trait stone",
      category: 'trait',
      price: 0,
      redeemType: 'equip',
    },
    {
      name: 'long forgotten coin',
      category: 'currency',
      price: 2000,
      redeemType: 'currency',
    },
    {
      name: 'trait shard',
      category: 'currency',
      price: 1000,
      redeemType: 'currency',
    },
    {
      name: 'quest ticket',
      category: 'currency',
      price: 0,
      redeemType: 'currency',
    },
    {
      name: 'fragmented soul essence',
      category: 'currency',
      price: 0,
      redeemType: 'currency',
    },
    {
      name: 'lifeshard',
      category: 'currency',
      price: 0,
      redeemType: 'currency',
    },
    {
      name: 'south shore pearl',
      category: 'misc',
      price: 500,
      redeemType: 'activities',
    },
    {
      name: 'iridescent pearl',
      category: 'misc',
      price: 1000,
      redeemType: 'activities',
    },
    {
      name: 'hathars eye',
      category: 'misc',
      price: 2000,
      redeemType: 'activities',
    },
    {
      name: 'corrupted pearl',
      category: 'misc',
      price: 2000,
      redeemType: 'activities',
    },
    {
      name: 'snow cat',
      category: 'misc',
      price: 1000,
      redeemType: 'activities',
    },
    {
      name: 'snow fish',
      category: 'misc',
      price: 1000,
      redeemType: 'activities',
    },
    {
      name: 'snow mammoth',
      category: 'misc',
      price: 1500,
      redeemType: 'activities',
    },
  ];
  private _redeems: gameitems[] = [];

  //#endregion

  getItems(): gameitems[] {
    return this._database;
  }

  getRedeems(): gameitems[] {
    return this._redeems;
  }

  getByCategory(category: string): gameitems[] {
    return this._database.filter((items) => items.category === category);
  }

  getOne(name: string): gameitems[] {
    name.trim().toLowerCase();
    return this._database.filter(
      (items) =>
        items.name.toLowerCase() === name ||
        items.name.toLowerCase().includes(name)
    );
  }

  redeemOne(item: gameitems): void {
    this._redeems.push(item);
  }
}
